name: Setup Rust
description: Install a Rust toolchain, initialize the cache, and optionally install cargo tools.
inputs:
  toolchain:
    description: Rust toolchain to install.
    required: true
  components:
    description: Comma-separated Rust components to install.
    required: false
    default: ""
  cargo-hack:
    description: Whether to install cargo-hack.
    required: false
    default: "false"
  cargo-nextest:
    description: Whether to install cargo-nextest.
    required: false
    default: "false"
  cargo-llvm-cov:
    description: Whether to install cargo-llvm-cov.
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - name: Install Rust
      if: ${{ inputs.components == '' }}
      uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
      with:
        toolchain: ${{ inputs.toolchain }}
    - name: Install Rust
      if: ${{ inputs.components != '' }}
      uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}
    - name: Initialize cache
      uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
    - name: Install cargo-hack
      if: ${{ inputs['cargo-hack'] == 'true' }}
      uses: taiki-e/install-action@74e87cbfa15a59692b158178d8905a61bf6fca95 # v2.75.20
      with:
        tool: cargo-hack
    - name: Install cargo-nextest
      if: ${{ inputs['cargo-nextest'] == 'true' }}
      uses: taiki-e/install-action@61debcf76ed7a18a8e22671693dd552bf6e5c67e # cargo-nextest
    - name: Install cargo-llvm-cov
      if: ${{ inputs['cargo-llvm-cov'] == 'true' }}
      uses: taiki-e/install-action@fe523c2f1957c9c709086afaae6c46defc8a41c5 # cargo-llvm-cov
